// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC1Qhgphnv5V13n_IfuBL10orSUCyEOvw',
    appId: '1:22718524512:web:53a52316ca7637e195a705',
    messagingSenderId: '22718524512',
    projectId: 'addnote-76856',
    authDomain: 'addnote-76856.firebaseapp.com',
    storageBucket: 'addnote-76856.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo8QJkj87LKqqw4Ywc0vCaLY3SrAew5TY',
    appId: '1:22718524512:android:8beff3773dafea8e95a705',
    messagingSenderId: '22718524512',
    projectId: 'addnote-76856',
    storageBucket: 'addnote-76856.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_R6B-nDdVRt5tekUTi4EbgQdTE0Hy6_A',
    appId: '1:22718524512:ios:5366c0b076bf279295a705',
    messagingSenderId: '22718524512',
    projectId: 'addnote-76856',
    storageBucket: 'addnote-76856.appspot.com',
    iosClientId: '22718524512-62t8tapvi61m090dhi0vtm04ao9bftv6.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.mynotes',
  );
}
